language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - "stable"

env:
  GO111MODULE=on

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
  - make deps

script:
  - make test
  # run coverage only if token is present
  - (test $COVERALLS_TOKEN && $GOPATH/bin/overalls -project=github.com/hellofresh/logging-go -covermode=count) || echo "Skipping coverage tests due to missing token"
  - (test $COVERALLS_TOKEN && $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN) || echo "Skipping coverage tests due to missing token"
